kccistc/intel-03

class01/homework/YEAJIN/README.md
class02/homework/YEAJIN/README.md
class02/homework/YEAJIN/\

Class01 hw2 amaziniverse

---

class01/README.md
class02/README.md

README 파일 이름 추가

---

class01/README.md
class02/README.md

HW3 change README.md

---

class01/homework/parkjinwuk/hw1_day06_CNN_practices/animal.py
class01/homework/parkjinwuk/hw1_day06_CNN_practices/flower.py
class01/homework/parkjinwuk/hw1_day06_CNN_practices/flower2.py
class01/homework/parkjinwuk/hw1_day06_CNN_practices/wally.py

class01_hw1

---

.gitmodules

Class01 - Mini Project - team5

---

class01/mini-project/team2/README.md

Class01 - Mini Project - team2 UPDATE Readme.md

---

class02/homework/KwonGangHyeon/hw1/led.py

Class02_hw1_아두이노LED제어_권강현

---

class02/homework/woochangmin/led.py

Class02_hw1_아두이노LED제어_우창민

---

class02/homework/myungjun/hw1/led.py

Class02_hw1_아두이노LED제어_김명준

---

class02/homework/parkyonggeun/hw2/factory.py

Class02 과제2 멀티쓰레딩 카메라 출력 구현 - 박용근

---

class02/homework/parkyonggeun/hw3/DeiT-Tiny/openvino.xml
class02/homework/parkyonggeun/hw3/EfficientNet-B0/openvino.xml
class02/homework/parkyonggeun/hw3/EfficientNet-V2-S/openvino.xml
class02/homework/parkyonggeun/hw3/MobileNet-V3-large-1x/openvino.xml
class02/homework/parkyonggeun/hw3/hw3_template.md

모델별 bin, xml 파일 총 4쌍 추가
hw3_template.md 작성

Class02 과제3 OTX를 이용한 model training - 박용근

---

class02/homework/KimGyuwon/hw2/factory.py

class02 과제2 멀티쓰레딩 카메라 출력 구현 - 김규원

---

class02/homework/KimGyuwon/hw3/DeiT-Tiny/openvino.xml
class02/homework/KimGyuwon/hw3/EfficientNet-B0/openvino.xml
class02/homework/KimGyuwon/hw3/EfficientNet-V2-S/openvino.xml
class02/homework/KimGyuwon/hw3/MobileNet-V3-large-1x/openvino.xml
class02/homework/KimGyuwon/hw3/hw03_template.md

class02 과제3 OTX를 이용한 model training - 김규원

---

class02/homework/KwonGangHyeon/hw2/factory.py

class02 과제2 멀티쓰레딩 카메라 출력 구현 PR입니다.

class02 과제2 멀티쓰레딩 카메라 출력 구현 - 권강현

---

class02/homework/parkjinwuk/hw1/led.py
class02/homework/parkjinwuk/hw2/factory.py

Class02 과제2 멀티쓰레딩 카메라 출력 구현 - 박진욱

---

class02/homework/KwonGangHyeon/hw3/DeiT-Tiny/openvino.xml
class02/homework/KwonGangHyeon/hw3/EfficientNet-B0/openvino.xml
class02/homework/KwonGangHyeon/hw3/EfficientNet-V2-S/openvino.xml
class02/homework/KwonGangHyeon/hw3/MobileNet-V3-large-1x/openvino.xml
class02/homework/KwonGangHyeon/hw3/hw03_template.md

class02 과제3 OTX를 이용한 model training PR입니다.

class02 과제3 OTX를 이용한 model training - 권강현

---

class02/homework/HongJongHyun/hw2/factory.py

Class02 과제2 멀티쓰레딩 카메라 출력 구현 - 홍종현

---

class02/homework/HongJongHyun/hw3/DeiT-Tiny/openvino.xml
class02/homework/HongJongHyun/hw3/EfficientNet-B0/openvino.xml
class02/homework/HongJongHyun/hw3/EfficientNet-V2-S/openvino.xml
class02/homework/HongJongHyun/hw3/MobileNet-V3-large-1x/openvino.xml
class02/homework/HongJongHyun/hw3/README.md

**Jerry 강사**님께서 5번부터 내용을 도와주셨습니다.
- git lfs 충돌 관련 해결
```
git rm --cached -r .
git reset --hard
git rm .gitattributes
git reset .
git checkout .
```
- git log에서 출력되었던 커밋 사이에 merge된 커밋내역 있었습니다. 
-> 알려주신 rebase로 hw3만 push하려 했지만, 다른 사람의 커밋내역까지 같이 딸려오는 현상이 있었습니다. 
-> git 그래프를 확인후 제 hw3 기록이 남도록 rebase를 다시 진행하였습니다.

class02 과제3 OTX를 이용한 model training - 홍종현

---

class02/homework/KwonGangHyeon/final/factory.py

Class02_hw4_Smart_Factory_최종_권강현

---

class02/homework/KimGyuwon/final/factory.py

Class02_hw4_Smart_Factory_최종_김규원

---

README.md

Team project setup - 권강현

---

README.md

Team04 Update README.md
